version: '3.6'

services:
  postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admire

volumes:
  postgres:
